### ISSUE TITLE
Memory leakage issue

### ISSUE THREAD

**Issue by rahulrkr08** [QubitProducts/qubit-react#29]
We are using server side rendering of react components. So, `<QubitReactWrapper />` component is trying to create new component in every refresh of the page. But `bootstrapWrapper()` is searching that if any namespace is already created (window.__qubit.....) then its pushing new component to the existing object, which is getting increased the size of `window` object in server in every refresh.

https://github.com/QubitProducts/qubit-react/blob/accfbadfbd1baca29223b9422a928e25911e49f8/wrapper/QubitReactWrapper.js#L27

**Comment by KwanMan** [comment]
@rahulrkr08 The wrapper shouldn't be loaded during SSR, it checks for the window object

https://github.com/QubitProducts/qubit-react/blob/accfbadfbd1baca29223b9422a928e25911e49f8/wrapper/index.js#L5

Do you manually create a `window` global?

**Comment by KwanMan** [comment]
@rahulrkr08 The wrapper shouldn't be loaded during SSR, it checks for the window object

https://github.com/QubitProducts/qubit-react/blob/accfbadfbd1baca29223b9422a928e25911e49f8/wrapper/index.js#L5

Do you manually create a `window` global?

**Comment by rahulrkr08** [comment]
Thanks @KwanMan got the issue, one of our plugin is creating window object.
